### ISSUE TITLE
reload config 

### ISSUE THREAD

**Issue by digitalysin** [devopsfaith/krakend#108]
figuring out, does krakend currently support reloading config files without restarting the krakend itself ?

for example : 

`krakend -c config.json --reload`

**Comment by kpacha** [comment]
hi @digitalysin ! welcome to the KrakenD community!

**TL;DR: no, this feature is not supported by design**

here you can find the reasons and possible alternatives

- https://github.com/devopsfaith/krakend/issues/100#issuecomment-373125906
- https://github.com/devopsfaith/krakend/issues/31#issuecomment-355857735

**Comment by alombarte** [comment]
Although we are not going to support hot reload of the gateway configuration because pipes are built at startup time for performance reasons, you might want to have a look at the excellent project confd by @kelseyhightower and adapt KrakenD to make use of it.  You could restart the server "automagically" when the configuration changes.

**Comment by arturoeanton** [comment]
I made one POC about this (reloading config / hot reload).
[https://github.com/arturoeanton/poc-krakend](https://github.com/arturoeanton/poc-krakend)
This is only POC becouse we need change kraken and gin.
I made pull request to Gin (if Gin approbal pull request I will make pullrequest in lura )
