### ISSUE TITLE
Content-Length is not being proxied

### ISSUE THREAD

**Issue by montenegrodr** [devopsfaith/krakend#129]
Running the simplest example copied from [Library Usage](https://github.com/devopsfaith/krakend#library-usage) - the same exact code. With this configuration.json:
```
{
  "version": 2,
  "name": "My lovely gateway",
  "port": 8080,
  "host": [
    "http://127.0.0.1:8080"
  ],
  "endpoints": [
    {
      "endpoint": "/",
      "method": "POST",
      "backend": [
        {
          "host": [
            "http://127.0.0.1:8000"
          ],
          "encoding": "json"
        }
      ],
      "headers_to_pass": [
        "Content-Length",
        "Content-Type",
        "Accept",
        "Host",
        "User-Agent"
      ]
    }
  ]
}
```
I am not getting `Content-Length` on my CherryPy service. It's possible to reproduce with this request:

```
curl --fail -X POST -H 'Content-Type: application/json' -H 'Content-Length: 22' -H 'Accept: json' -d '{"text": "0000000000"}' 'http://localhost:8080' 
```

All other headers and content are proxied correctly. The problem is only with `Content-Length`.

**Comment by kpacha** [comment]
hi @montenegrodr , welcome to the KrakenD community.

The behaviour is related with the `net/http` package: 

> For client requests, certain headers such as Content-Length and Connection are automatically written when needed and values in Header may be ignored.

https://golang.org/src/net/http/request.go?s=#L157

All the layers in the pipe do propagate all the defined headers, but the internal `newTransferWriter` function of the `net/http` package assigns the value `t.ContentLength = rr.outgoingLength()` and does not propagate the received `Content-Length` header.

Following the white rabbit into the hole, I found the `NewHTTPProxyDetailed` middleware is not defining the `requestToBackend.ContentLength` property because it always sends chunked requests.

Without reading the request body before forwarding it, the only way I can see to allow the propagation of the `Content-Length` header is to include some 'nasty hack', such as parsing the received header and if it contains an integer, setting the `requestToBackend.ContentLength` property... allowing some other weird situations if the clients do not send the proper value for the header.

Any ideas?

**Comment by kpacha** [comment]
here is an example of my dumb proposal: https://github.com/devopsfaith/krakend/commit/b9093c0a812eefeaed131d762ea4af577d81eb0c

reading the actual `request.Body` would require some extra calculations and allocations, but the required code would be placed there too

**Comment by kpacha** [comment]
fixed, thanks!
