### ISSUE TITLE
Support for gRPC 

### ISSUE THREAD

**Issue by elitegit** [devopsfaith/krakend#142]
Hi
First of all, thanks a lot for the great job. Do you have any plan to add support for gRPC routing as well. Can you share some ideas/solutions in here how to implement it so someone else can also help with that.

Thanks

**Comment by alombarte** [comment]
Hello @elitegit,

gRPC is a possible implementation for KrakenD as it is based on the HTTP2 layer. So far is not a priority for us and never spent the time to put it in motion. I can tell you that this is not something included in our 0.6 roadmap (after summer).

As per the ideas on how to do it:
- In the *router* level you need to build the gRPC server and connect the handler generators to the proxy pipes. This implies creating the `github.com/devopsfaith/krakend/router/grpc` package and implementing the required interfaces `router.Router` and `router.Factory`.
- It might be necessary to adjust something at configuration level and in the proxy if anything extra comes out, although at the end of the day gPRC goes over HTTP2

The gRPC implementation it's far away in the roadmap, but we are totally open to implement it ourselves given there is interest. I will leave this issue open for a while, if I get enough 👍 to this comment I will put it closer to reality :)

**Comment by ivanjaros** [comment]
Hi, I am just wondering - If i need api gateway to do auth and proxy directly or aggregate and transform, and all backend is gRPC and the front end has grpc proto definition that can serve pb and json(either via twirp or grpc-gateway), does it make sense to use kraken instead of just implementing grpc server?

**Comment by kpacha** [comment]
@ivanjaros I think your question is independent of the transport/encoding protocol. Here are my main points:

- You can always build an in-house solution, but you'll need to code and maintain it.
- The initial specs tend to be far from complete (in my experience), so double check the generated estimates because their confidence is usually very low. In my opinion, it is also very important to think about rate-limiting, circuit breakers, service discovery, concurrent requests, metrics, logs, instrumentation, etc.
- There are many other things that you can consider such as flexibility in the manipulation of the data or the tolerance to errors.
- It's dangerous to think about this layer as just a router because that pattern introduces high coupling between your clients and the actual backend services
- This project has more than 2 years of contributions and there are big internet companies using it. We offer support services for those companies, so they can replace their in-house solutions easily and without investing more than one or two engineers part time

Cheers

**Comment by kpacha** [comment]
@elitegit the PR #255 and #256 have been merged so the next released will support plugins... and here is an example of what can you do with it https://www.krakend.io/blog/krakend-grpc-gateway-plugin/
