### ISSUE TITLE
Is it possible to header transformer?

### ISSUE THREAD

**Issue by iamgoangle** [devopsfaith/krakend#144]
Is it possible to have configuration transform header? for example I would like to create x-tracing-id=<uuid> or custom header. I'm not sure this feature are available or not, if it there can you please suggest?

**Comment by taik0** [comment]
Hi @iamgoangle,

If what you want, is be able to modify the KrakenD Framework, read this issue since it has a lot of  information: 
https://github.com/devopsfaith/krakend/issues/43#issuecomment-332263763

If you are using KrakenD-CE here you have an example of how to do it via configuration (using [krakend-martian](https://github.com/devopsfaith/krakend-martian)) as it already provides tools to modify requests and responses:
https://github.com/devopsfaith/krakend-ce/blob/master/krakend.json#L35-L63

You can also write your own custom martian modifier:
http://www.krakend.io/blog/website-development-as-a-sysadmin/

If you are doing tracing in you application, I encourage you to take a look to our [krakend-opencensus](https://github.com/devopsfaith/krakend-opencensus) module as it provides tracing and stats for a lot of backends (zipkin, jaeger, influxdb, prometheus, aws xray).

The krakend-opencensus module it's already provided in KrakenD-CE.

Hope it helps you!

**Comment by iamgoangle** [comment]
Thanks so much.
