### ISSUE TITLE
Backend requests do not have a forwarded Host header

### ISSUE THREAD

**Issue by lindleywhite** [devopsfaith/krakend#245]
When making a request within NewHTTPProxyDetailed (https://github.com/devopsfaith/krakend/blob/master/proxy/http.go#L49) net/http's http.Request honors only the request.Host value as the one sent to the upstream. Even if the Host header is set and copied to the Request it won't apply that to the Request.Write.

Would it be worthwhile to add a configuration parameter for a service level config to forward Host to the upstream? 

There are quite a few services that need external level Host headers that might not be the same as internal DNS structures.

**Comment by taik0** [comment]
Hi @lindleywhite and welcome to the KrakenD community!

Seems like golang net/http promotes the Host header to `request.Host` and it's removed from the Headers map and then it is not copied to the backend request even if you set it in `headers_to_pass`.
It should be easy to check if request.Host is not empty and is set in `headers_to_pass` to add the Header again to the backend request.

I will discuss with @kpacha about this behaviour. Thank you for reporting!

**Comment by kpacha** [comment]
@lindleywhite , I've created a small [martian modifier](https://github.com/kpacha/martian-components/tree/master/header/host) so the host header to add to the requests to a given backend can be defined at the configuration.

```
    ...
    "host": [ "http://127.0.0.1:8000" ],
    "endpoints": [
        {
            "endpoint": "/a",
            "backend": [
                {
                    "url_pattern": "/__debug/backend-1",
                    "extra_config": {
                        "github.com/devopsfaith/krakend-martian": {
                            "header.Host": { "host": "api.vhost1.tld" }
                        }
                    }
                },
                {
                    "url_pattern": "/__debug/backend-2",
                    "extra_config": {
                        "github.com/devopsfaith/krakend-martian": {
                            "header.Host": { "host": "vhost2.tld" }
                        }
                    }
                },
                {
                    "url_pattern": "/__debug/backend-3"
                }
            ]
        }
    ]
    ...
```

with this config, all the backends are using the same host for building the request URL, but the backend server will get 3 requests with different values for the `Host` header. The received requests will be:

| # | backend | path | host header |
| --- | --- | --- | --- |
| 1 | http://127.0.0.1:8000 | /__debug/backend-1 | api.vhost1.tld |
| 2 | http://127.0.0.1:8000 | /__debug/backend-2 | vhost2.tld |
| 3 | http://127.0.0.1:8000 | /__debug/backend-3 |  |

I think we can't just use whatever the client sent, because it couples the client with the backend details and it doesn't work with pipes consuming several backend services

We'll try to include it into the next release of the CE

Again, thanks for pointing it out

**Comment by lindleywhite** [comment]
I understand that need to keep it agnostic from the multiple requests perspective, but if you're using strictly as a reverse-proxy that seems like an overkill of configuration needed. 

Would it be better to just allow it to be a passed Header in allowed_headers and if it's in the list of Headers that are set - set it to the upstream request? 

I'm not looking at using krakend-ce, I'm using it more in the framework. For now I've built my own BackendFactory, but it would be great to not have to do that.

**Comment by nicocesar** [comment]
Is this still open? I can't reproduce it.

**Comment by kpacha** [comment]
... I totally forgot about this issue.

The custom modifier didn't make it to the CE because there is already a modifier in the martian project for that: `url.Modifier` (https://github.com/google/martian/wiki/Modifier-Reference#url)

```
{
  "url.Modifier": {
    "scope": ["request"],
    "host": "www.google.com"
  }
}
```

**Comment by taik0** [comment]
This may come a bit old now, but this is the best way to change the Host header in the request that goes to the backend instead of using the url.Modifier (that makes the request to go to that host):
```
"extra_config": {
    "github.com/devopsfaith/krakend-martian": {
        "header.Modifier": { 
            "scope": ["request"],
            "name": "Host",
            "value": "api.vhost1.tld"
         }
    }
}
```
