### ISSUE TITLE
Expanding collection response with sub-requests

### ISSUE THREAD

**Issue by DeyLak** [devopsfaith/krakend#257]
I have read about the new flatmap feature and read through some related issues, like: #227, #220 , #194 etc. 
But I didn't find an answer for this case:
I have a collection response from one of my services like this: 
```
[
  {
    "id": 1,
    "operation": 1,
    ...
  },
  {
    "id": 2,
    "operation": 2,
    ...
  },
  {
    "id": 3,
    "operation": 3,
    ...
  }
]
```

And I have other service, that has `operations/{id}` endpoint, that returns a single object, or `operations/`endpoint, that returns collection of all operations. I want to initiate subsequent requests for each collection item, or merge 2 collections by id, to receive operation object and generate a response like this: 
```
[
  {
    "id": 1,
    "operation": {
      "id": 1,
      "name": "Op1"
    },
    ...
  },
  {
    "id": 2,
    "operation": {
      "id": 2,
      "name": "Op2"
    },
    ...
  },
  {
    "id": 3,
    "operation": {
      "id": 3,
      "name": "Op3"
    },
    ...
  }
]
```

Is this possible with current flatmap configuration options? I understand the performance consequences of this, but I'm currently in search of the fastest option to merge existing backends.

**Comment by DeyLak** [comment]
Any response on this, please?

**Comment by kpacha** [comment]
hi @DeyLak and welcome to the KrakenD community!

first of all: sorry for the delayed response. we've been super focused on getting ready for the devops.barcelona

in order to properly answer your question, I think there are 3 different parts:
- so far, the flatmap feature just supports 2 operations: `move` and `delete`. We want to add an `append` (https://github.com/devopsfaith/flatmap/issues/4) and maybe a `merge`. but all these operations are intended to modify the response, not to select elements from it as arguments for some other component.
- the sequential merger can't iterate over some collection in the response. the team building the endpoint at the gateway should already now the number of calls to backends involved in the workflow
- we are working on a LUA module (https://github.com/devopsfaith/krakend-lua) that will allow users to define their own logic at some parts of the pipe without recompiling the KrakenD binary

The second point is critical for the performance of the endpoint and the entire gateway, because it could be possible to get a collection with hundreds, thousands or millions of elements... just imagine the impact of making that extra N requests

<img width="943" alt="Captura de pantalla 2019-06-05 a las 15 24 28" src="https://user-images.githubusercontent.com/1307694/58959792-1a797880-87a6-11e9-9696-7f79d19b2f89.png">
