### ISSUE TITLE
Flexible Configuration

### ISSUE THREAD

**Issue by pthelusma** [devopsfaith/krakend#271]
I am currently doing a proof-of-concept on KrakenD. One requirement that I have is that configuration needs to be dynamically built as the environments built are dynamic as well. I looked into flexible configuration but it is not immediately obvious how one would use environment variables to determine the proper backends. Note that the URL of the backends are determined at the time of deployment. Is there a way to inject environment variables into the configuration with flexible configuration enabled?

**Comment by kpacha** [comment]
No, the flexibleconfig module does not load variables from the environment.

I think the easiest way to do what you want is to define a settings file (so you can refer to each value by its variable name) and run a small shell script to populate the values as defined at the system env_vars.

cheers

**Comment by geshan** [comment]
+1 I want to do it too, it should be easier than this. Even the Env variable config didn't work easily - https://www.krakend.io/docs/configuration/environment-vars/. And is there a way to replace parts of the URL or the host like `https://{{.variables.subdomain}.domain.com/api` where subdomain comes from varaiable.json in setting dir.

**Comment by vahdet** [comment]
The `Overriding properties in any nesting level` section of documentation [here](https://www.krakend.io/docs/configuration/environment-vars/) states `env` function can be used in any level. However, I could not make it work when I want to replace endpoint hosts depending on the environment. That's sad.

**Comment by alombarte** [comment]
@vahdet A quick example to demonstrate how to inject an environment variable containing the number of running instances into KrakenD and use it to apply rate limiting and similar features:

Given a configuration file:
 ```
{
   "version": 2,
   "all-the-rate-limit-boilerplate-here": {{ env "NUM_PODS" | div 100 }}
 }
```
 You can execute krakend like this:
```
FC_ENABLE=1 \    
FC_OUT=compiled.json \
NUM_PODS=3 krakend check -c krakend.json
```
And you get in the compiled.json the following content:
```
{ 
  "version": 2,
  "all-the-rate-limit-boilerplate-here": 33
}
```
Hope this helps to illustrate the point. If you have problems with flexible configuration, please open a new issue rather than commenting very old closed issues (which I accidentally saw)
