### ISSUE TITLE
Who is using krakend?

### ISSUE THREAD

**Issue by boazlautman** [devopsfaith/krakend#273]
Who is using krakend?
Is it a stable and fast?
Any pitfalls in production?

**Comment by alombarte** [comment]
Ho @boazlautman, KrakenD has been running in production for almost three years now. During this time we did minor corrections and added a lot of features.

The product is used across the world by thousands of developers. You can check the list of issues on Github as it's the only way we have to manage issues.

It is VERY stable, and VERY fast. But don't take me word for granted when I say it's the fastest. I always recommend all developers to performance-test KrakenD against all others within your scenario and see the difference.

About the who, there are a lot of companies that use it. Many I cannot share because I am not allowed to, but this is a good reading start https://www.krakend.io/who-is-using-krakend/

Hope to see you on board soon
