### ISSUE TITLE
Required backends requests

### ISSUE THREAD

**Issue by ihippik** [devopsfaith/krakend#288]
**Is your feature request related to a problem? Please describe.**
If at least one of the parallel queries to the backend is unsuccessful, then in the resulting response there are no traces from it (StatusOK is returned).
If the request is only one. then StatusInternalServerError returns.

**Describe the solution you'd like**
I want to be able to get a backend response with an error code and give it to the end user.
To do this, I introduce a special property of the request, the response of which is very important to the user. Therefore, I return such requests with high priority (only it) and as it is (successful and not successful).

**Comment by kpacha** [comment]
@ihippik why not using the `detailed_error` feature? it introduces a struct into the final response with the error description and status code

```
{
	"error_backend_b": {
		"http_status_code": 404,
		"http_body": "404 page not found"
	},
	"foo": 42
}
```

check it in action at the integration tests:

- config: https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/krakend.json#L385-L407

- the spec (request/response): https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/specs/detail_error.json

**Comment by ihippik** [comment]
@kpacha yes, I saw this feature 👍 but:
Our API focuses on response codes and this is logical, because they are for this and invented)
1) All our http-clients process the http status code (if 200 always arrives, then all of them will have to be rewritten)
2) In aggregate requests there is one leader, without which it does not make sense to give a partial answer.
3) The logic of our infrastructure is built on the processing of HTTP status codes.
4) We want to filter logged requests by HTTP codes.
5) Backend errors in the response - this is additional logic on the frontend

**Comment by kpacha** [comment]
I get your point but this is one of the architectural decisions we made when started the project. It's not written in stone but it's kinda intrinsical to the design and development. 

these are some of the concerns/reasons behind it:

- status code is just for http(s). other transports do not use it and the proxy layer should be as transport agnostic as possible.
- semantics of the status codes are not well understood/used
- in the final gateway response, there is no way to properly offer a distinction between the status code from the backend and the one from the gateway itself. that's why all errors external to the KrakenD are translated into a `500 internal server error`
- in order to offer a gracefully degraded service when some backends fail, we leave the decission to the client adding the header `X-Krakend-Completed: false` (and also adding the `detailed_error` feature)
- the clients should be designed to consume their use cases from the api gateway, not through it as a glorified proxy. In doing that we're decoupling them from the backend implementations that could change and evolve

there are several issues over the krakend projects regarding the handling of the status codes, I hope the debates help to better make my point:

https://github.com/devopsfaith/krakend/issues/283
https://github.com/devopsfaith/krakend/issues/102
https://github.com/devopsfaith/krakend-ce/issues/31

my bottomline would be: since the api gateway has its own logic, the response code should be related to that and not to the backends, just as an api shouldn't expose errors from its database or an external service it's consuming

**Comment by ihippik** [comment]
I understand your point of view and it really has a place to be, but my feature is optional and it does not influence those users in any way. who do not need it. Naturally, it will be used only for http-transport. She will not affect other requests.

I saw these questions in issues and in FAQ, so there is a demand for it. But most importantly, we need it;)

**Comment by ihippik** [comment]
@kpacha The last and most important argument ;)
Hiding 404 errors is not explicit behavior.

**Comment by NoiseByNorthwest** [comment]
@kpacha
> that's why all errors external to the KrakenD are translated into a 500 internal server error

But what about upstream response reading errors & timeout ? Which are covered by 2 well-defined & supported (e.g. all mainstream HTTP servers) status codes as I said in #347 ?

**Comment by kpacha** [comment]
@NoiseByNorthwest as said:
>the clients should be designed to consume their use cases from the api gateway, not through it as a glorified proxy. In doing that we're decoupling them from the backend implementations that could change and evolve

> my bottomline would be: since the api gateway has its own logic, the response code should be related to that and not to the backends, just as an api shouldn't expose errors from its database or an external service it's consuming
