### ISSUE TITLE
Circuit breaker failure scenario

### ISSUE THREAD

**Issue by nvlan** [devopsfaith/krakend#381]
Hello,

I have a microservice that when called on a specific endpoint, it takes about 5 seconds to reply. The backend in kraken is configured with the following extra_config stanza:

`"github.com/devopsfaith/krakend-circuitbreaker/gobreaker": {`
`              "interval": 60,`
`             "timeout": 10,`
`            "maxErrors": 1,`
`           "logStatusChange": true`
`}`

When I call on the endpoint with a global timeout of 3 seconds, I receive a 500 error from kraken and see the following (expected) log:

`[GIN] 2020/06/24 - 01:05:32 | 500 |    3.0019244s |      172.17.0.1 | GET      /krakend/buscar/robertocarlos
Error #01: context deadline exceeded
`

However, the next call I try to the same endpoint after those 5 seconds does go through, when I would expect the circuit breaker to kick-in and stop sending requests to the backend for the next 60 seconds. What would be considered as an "error" for the circuit breaker to engage? How could I properly test the circuit breaker mechanism?

Thanks a lot, and kind regards!

**Comment by kpacha** [comment]
If the backend takes more than the defined timeout to return, the context gets canceled and it counts as an error for the circuit breaker. With your configuration, next error after `1` will open the circuit as you can see in this log (the circuit breaker opening the circuit is logged before the related request because the status is changed before returned the request that triggers such change):

```
[GIN] 2020/06/24 - 19:08:08 | 500 |  3.004040915s |             ::1 | GET      /cache/1
Error #01: context deadline exceeded
2020/06/24 19:08:13  WARNING: circuit breaker named '' went from 'closed' to 'open'
[GIN] 2020/06/24 - 19:08:13 | 500 |  3.004549941s |             ::1 | GET      /cache/1
Error #01: context deadline exceeded
[GIN] 2020/06/24 - 19:08:15 | 500 |      80.126µs |             ::1 | GET      /cache/1
Error #01: circuit breaker is open
```

So, if you aren't seeing such change it must be due your backend is not always exceeding the timeout
