### ISSUE TITLE
Empty URL and Path in proxy.Request

### ISSUE THREAD

**Issue by zean00** [devopsfaith/krakend#411]
**Describe the bug**
I'm trying to create custom proxy plugin , and requires to process request URL / path, but the value of URL and Path in proxy.Request is always empty

**To Reproduce**
Create custom plugin which read request URL / Path and print out to logger

**Expected behavior**
The URL / Path value is not empty and should be copying from http Request

**Additional context**
I've check the code on gin router, it seems those value is never set, is it by design? If so what is the reason not including those value to the proxy.Request

**Comment by kpacha** [comment]
the URL is generated at the `proxy.NewRequestBuilderMiddleware`, injected just before the `BackendFactory`: https://github.com/devopsfaith/krakend/blob/master/proxy/factory.go#L84-L92

the URL should not be copied from the http Request because KrakenD is not a reverse proxy. The URL is built by injecting the received url params into the provided url pattern
