### ISSUE TITLE
[question] How to set up bloomfilter?

### ISSUE THREAD

**Issue by GiteItAwayNow** [devopsfaith/krakend#413]
Hi guys,

I'm trying to make bloomfilter work with my app but when I start the krakend server ) got the following error in the log

`[KRAKEND] 2020/10/05 - 20:08:28.813 ▶ ERROR Couldn't register krakend-bf:1234 in consul: unable to create the consul client: no config`

I also can start bloomfilter with KrakenD Playgroung - I get the same error.

I assume that I have to use consul.io. I've installed it and registered krakend-bf service but no luck.

Could you point me the direction to move with this issue?

**Comment by kpacha** [comment]
the error is only critical if you're relying on consul in order to identify your krakend instances but doing it is not mandatory. as the playground demonstrates, you can just create a remote client for the bloomfilter server https://twitter.com/devopsfaith/status/1313155919312805889

the consul configuration is not included with all the other SD in the documentation because the component is used just as way to register the instance itself, not for consuming data from the SD serverr

**Comment by GiteItAwayNow** [comment]
Hi @kpacha ,

Thanks a lot for your asnwer!

Ok. So I can use bloomfilter without consul, can't I? Or I have to set up it anyway?

It seems that you sent another link. I tried playground but I ge tthe same errror. 
Could you tell me where I can see how to configure it properly?
Thank you!

**Comment by kpacha** [comment]
>So I can use bloomfilter without consul, can't I?

yes, indeed

>It seems that you sent another link. I tried playground but I get the same errror.
Could you tell me where I can see how to configure it properly?

my bad, I fixed the link to the jwt revoker using https://godoc.org/github.com/devopsfaith/bloomfilter/rpc/client

bottomline: consul is useful for discovery all the krakend instances, but you can go with any other method (such as static ip and port)
