### ISSUE TITLE
Sequential Host request

### ISSUE THREAD

**Issue by mahalyka** [devopsfaith/krakend#457]
This feature is relate with sequential proxy that existing now in the krakenD. But how about when we need to hit same endpoint in many host with sequential connection? I mean...i have this sampel:

```
"endpoint: "/v1/start",
"host" : {
"domainA.com:101",
"domainA.com:102",
"domainA.com:103"
}
```
How we able to hit the host sequentially. I mean this case is needed for many use case later. Also for POST Sequential Proxy Call.
So when we have a flag to activate a sequential host request. we can provide with this sampel config 👍 

```
"sequential_host" : {
"activate" : true,
"stop_status" : ["200", "201", "401", "400","403"]
}
```

> Goal for this: 
> -> Krakend hit "/v1/start", from "domainA.com:101", -> 500 then continue
> -> Krakend hit "/v1/start", from "domainA.com:102", -> 200 then stop then response send to client
> -> Krakend hit "/v1/start", from "domainA.com:103", -> Passed

**Comment by kpacha** [comment]
to me, this looks like more a retry strategy than a sequential proxy, since it deals with errors more than with composing responses.

krakend does not support retries by design (https://www.krakend.io/docs/extending/the-big-picture/#the-krakend-rules). clients should dealt with any possible error, not the gateway, because it's impossible to do such thing without knowing too much about the business logic and without impacting the environment.

cheers

**Comment by kpacha** [comment]
Thanks for opening the issue. We have discussed internally the consequences of putting this idea in motion but the technical implications are too high.
