### ISSUE TITLE
Cannot use a host with path

### ISSUE THREAD

**Issue by tchssk** [devopsfaith/krakend#66]
When I specify a `host` with path in the configuration file, it causes a panic.

Here is an example.

- This is a `host` without path. It's a valid host.

    ```
    https://api.github.com
    ```

- This is a `host` with path. It causes `errInvalidHost`.

    ```
    https://api.twitter.com/1.1
    ```

As a workaround, I put the path into `url_pattern`.

```json
{
  "url_pattern": "/1.1/statuses/home_timeline.json",
  "host": [
    "https://api.twitter.com"
  ]
}
```

However I feel it should be able to specify like below.

```json
{
  "url_pattern": "/statuses/home_timeline.json",
  "host": [
    "https://api.twitter.com/1.1"
  ]
}
```

**Comment by alombarte** [comment]
Hello @tchssk, thank you very much for your contribution, great to see you getting your hands dirty! Receive a warm welcome from the other side of the world.

I see the benefit and the practicality (from a code readable point of view) of separating the API version `/1.1/` from the url_pattern `/statuses/home_timeline.json`, but I see more this as a prefix for the url_pattern rather than becoming part of the hostname. 

If we modify it the host way then there are some drawbacks that might be unnoticed. To evaluate the host we have today a simple regexp in the code. That is there with the intention to be changed anytime as we don’t want to couple the host implementation to the http protocol (and net/http library). Why? In the 0.3.9 version (current) the syntax expects a URL but with the version 0.4 we open sourced the service discovery entries, for instance:

```
"url_pattern": "/1.1/statuses/home_timeline.json",
"sd": "etcd",
"host": [
     "time-line-service"
]
```
or
```
"url_pattern": "/1.1/statuses/home_timeline.json",
"sd": "dns",
"host": [
     "time-line-service"
]
```
vs
```
"url_pattern": "/1.1/statuses/home_timeline.json",
"sd": "static",
"host": [
     "https://time-line-1.local:8080",
     "https://time-line-2.local:8080",
     "https://time-line-1.local:8081",
     "https://time-line-2.local:8081"
]
```
Doors are open now to use also custom SD systems. Other protocols like gRPC, Thrift or whatever will join and you’ll see immediately that modifying the host is not an option. 

Note also that the host is also used for load balancing purposes. In the twitter example that you provided it is a single host (api.twitter.com) and the balancing is invisible to you because is a public api they handle their way, but when krakend is inside the VPC of the service the hosts are usually declared as the internal IPs or hostnames (last provided example) and krakend uses the different hosts of the same service to get the maximum speed.

Many clients mix versioning, so the usage of the version is delegated to the url_pattern anyway (as you wouldn’t declare two different hosts to declare 2 versions).

Does this make sense?

Thanks!

**Comment by tchssk** [comment]
Thank you for the detailed explanation. It makes sense. I'll close this issue.

Thank you.!
